trigger:
- master

variables:
- name: buildConfiguration
  value: release

pool:
 name: WindowsAgentPool
 
stages:
- stage: BuildSolution 
  jobs:
    - job: restoreAndBuild
      displayName: restore build and test
      steps:
      - task: UseDotNet@2
        displayName: Install dotnet 8 sdk
        inputs:
          packageType: 'sdk'
          version: '8.x'
          includePreviewVersions: true
          performMultiLevelLookup: true
          
      - task: DotNetCoreCLI@2
        displayName: restore packages
        inputs:
          command: restore
          projects: '**/*.csproj'
       
      - task: DotNetCoreCLI@2
        displayName: Build Projects
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)'

      - script: dotnet test **/tests/SampleAppForDevops.Tests/*.csproj  --configuration $(buildConfiguration) --collect "Code Coverage"
        displayName: Run Tests


    
    